include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - "test/.test_coverage.dart"
    - "test/fixtures/**"
    - "**/*.g.dart"
    - "**/version.dart"
linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
