include: ../../analysis_options.yaml
analyzer:
  exclude:
    - "test/.test_coverage.dart"
    - "test/fixtures/**"
    - "**/*.g.dart"
    - "lib/src/version.dart"
linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
