// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'src/mason_logger_test.dart' as src_mason_logger_test;
import 'src/stdio_overrides_test.dart' as src_stdio_overrides_test;

void main() {
  src_mason_logger_test.main();
  src_stdio_overrides_test.main();
}
