builders:
  inFileGenerationBuilder:
    import: "package:masonex/builders.dart"
    builder_factories: ["inFileGenerationBuilder"]
    build_extensions: {r"$lib$": ["brick.yaml"]}
    auto_apply: root_package
    build_to: source
