name: test

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/mason_logger.yaml
      - packages/mason_logger/**

  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/mason_logger.yaml
      - packages/mason_logger/**

jobs:
  build:
    defaults:
      run:
        working-directory: packages/mason_logger

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Verify CI Behavior
        run: dart test/ci.dart
